/* University of Lahore: MoU report, landscape A4, self-contained direct PDF download. */
(function(){
'use strict';
const fmt=v=>Number(v||0).toLocaleString('en-US');
const clean=v=>String(v==null?'':v).trim();
const valid=v=>!!clean(v)&&!['null','n/a','none','nan','not available','unclassified','...'].includes(clean(v).toLowerCase());
const group=(rows,k)=>{const m=new Map();for(const r of rows){const v=clean(r[k]);if(valid(v))m.set(v,(m.get(v)||0)+1);}return [...m].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));};
const unique=(rows,k)=>group(rows,k).length;
const palette={navy:[.052,.157,.245],green:[.035,.525,.413],blue:[.13,.39,.78],purple:[.46,.34,.76],gold:[.87,.54,.18],ink:[.08,.16,.24],grey:[.35,.43,.50],pale:[.957,.975,.987],line:[.84,.89,.93],white:[1,1,1]};
const winSpecial={'€':128,'‚':130,'ƒ':131,'„':132,'…':133,'†':134,'‡':135,'ˆ':136,'‰':137,'Š':138,'‹':139,'Œ':140,'Ž':142,'‘':145,'’':146,'“':147,'”':148,'•':149,'–':150,'—':151,'˜':152,'™':153,'š':154,'›':155,'œ':156,'ž':158,'Ÿ':159};
const hex=s=>{const bytes=[];for(const ch of String(s)){const v=ch.codePointAt(0);bytes.push(v>=32&&v<=126||v>=160&&v<=255?v:(winSpecial[ch]||63));}return bytes.map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();};
class PDF{
 constructor(){this.w=841.89;this.h=595.28;this.pages=[];this.commands=[];this.y=74;this.newPage('');}
 rgb(color,stroke=false){return color.map(n=>n.toFixed(3)).join(' ')+(stroke?' RG':' rg');}
 rect(x,y,w,h,color){this.commands.push(`${this.rgb(color)} ${x.toFixed(2)} ${(this.h-y-h).toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f`);}
 outline(x,y,w,h,color=palette.line){this.commands.push(`${this.rgb(color,true)} .8 w ${x.toFixed(2)} ${(this.h-y-h).toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re S`);}
 line(x,y,x2,y2,color=palette.line,width=.75){this.commands.push(`${this.rgb(color,true)} ${width} w ${x.toFixed(2)} ${(this.h-y).toFixed(2)} m ${x2.toFixed(2)} ${(this.h-y2).toFixed(2)} l S`);}
 text(value,x,y,size=10,bold=false,color=palette.ink){this.commands.push(`${this.rgb(color)} BT /${bold?'F2':'F1'} ${size} Tf 1 0 0 1 ${x.toFixed(2)} ${(this.h-y-size).toFixed(2)} Tm <${hex(value)}> Tj ET`);}
 wrap(text,maxWidth,size=9){const max=Math.max(9,Math.floor(maxWidth/(size*.53)));const lines=[];for(const para of clean(text).split(/\n/)){let current='';for(let word of para.split(/\s+/)){while(word.length>max){if(current){lines.push(current);current='';}lines.push(word.slice(0,max));word=word.slice(max);}if((current+' '+word).trim().length>max){if(current)lines.push(current);current=word;}else current=(current+' '+word).trim();}lines.push(current);}return lines.length?lines:['-'];}
 newPage(section='MOU & COLLABORATIONS'){this.commands=[];this.pages.push(this.commands);this.y=93;this.rect(0,0,this.w,6,palette.green);this.text('THE UNIVERSITY OF LAHORE',42,20,15,true,palette.navy);this.text('OFFICE OF EXTERNAL LINKAGES',42,41,8,true,palette.green);this.text(section.toUpperCase(),this.w-245,30,10,true,palette.navy);this.line(42,64,this.w-42,64);}
 heading(title,subtitle=''){this.text(title,43,76,18,true,palette.navy);if(subtitle)this.text(subtitle,44,101,9,false,palette.grey);this.line(43,122,this.w-43,122,palette.line);this.y=140;}
 foot(){this.pages.forEach((cmds,i)=>{cmds.push(`${this.rgb(palette.grey)} BT /F1 8 Tf 1 0 0 1 43 23 Tm <${hex('University of Lahore  |  Tentative Institutional Engagement Report')}> Tj ET`);cmds.push(`${this.rgb(palette.grey)} BT /F1 8 Tf 1 0 0 1 740 23 Tm <${hex(`Page ${i+1} / ${this.pages.length}`)}> Tj ET`);});}
 cards(items){const gap=13, w=(this.w-86-gap*(items.length-1))/items.length;items.forEach(([title,value],i)=>{const x=43+i*(w+gap);this.rect(x,this.y,w,88,palette.pale);this.outline(x,this.y,w,88);this.rect(x,this.y,w,4,[palette.green,palette.blue,palette.purple,palette.gold][i%4]);for(const [idx,line] of this.wrap(title.toUpperCase(),w-23,8).slice(0,2).entries())this.text(line,x+13,this.y+13+idx*11,8,true,palette.grey);this.text(fmt(value),x+13,this.y+48,23,true,palette.navy);});this.y+=107;}
 breakdownPage(title,subtitle,entries){this.newPage('Graphical Summary');this.heading(title,subtitle);if(!entries.length){this.text('No matching records',44,160,11);return;}const max=Math.max(1,...entries.map(e=>e[1]));const count=entries.length;const rowH=Math.min(38,Math.max(15,385/count));const labelW=270, plotW=455;entries.forEach(([name,v],i)=>{const y=this.y+i*rowH;const labels=this.wrap(name,labelW-10,rowH>=25?9:7).slice(0,rowH>=25?2:1);labels.forEach((line,j)=>this.text(line,44,y+1+j*10,rowH>=25?9:7,false,palette.ink));this.rect(319,y+3,plotW,Math.max(5,rowH-10),palette.pale);this.rect(319,y+3,plotW*v/max,Math.max(5,rowH-10),[palette.green,palette.blue,palette.purple,palette.gold][i%4]);this.text(fmt(v),781,y+1,9,true,palette.navy);});}
 table(title,heads,rows,widthWeights){const left=43,totalWidth=this.w-86,sum=widthWeights.reduce((a,b)=>a+b,0),widths=widthWeights.map(v=>v/sum*totalWidth);let continued=false;const begin=()=>{this.newPage('Detailed Reporting');this.heading(continued?title+' (continued)':title,'Source: currently selected MoU Excel records');this.rect(left,this.y,totalWidth,28,palette.navy);let x=left+8;heads.forEach((h,i)=>{this.wrap(h,widths[i]-13,8).slice(0,2).forEach((l,j)=>this.text(l,x,this.y+6+j*9,8,true,palette.white));x+=widths[i];});this.y+=28;continued=true;};begin();if(!rows.length){this.text('No records for current filters',44,this.y+18,10);return;}for(let ri=0;ri<rows.length;ri++){const cells=rows[ri].map((v,i)=>this.wrap(valid(v)?v:'-',widths[i]-13,8));const h=Math.max(27,12+Math.max(...cells.map(l=>l.length))*11);if(this.y+h>this.h-50)begin();if(ri%2===0)this.rect(left,this.y,totalWidth,h,palette.pale);let x=left+8;cells.forEach((lines,i)=>{lines.forEach((line,j)=>this.text(line,x,this.y+7+j*11,8,false,palette.ink));x+=widths[i];});this.y+=h;this.line(left,this.y,left+totalWidth,this.y);}}
 output(){this.foot();const objs=[null],add=o=>{objs.push(o);return objs.length-1;};const fa=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),fb=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'),root=add(''),kids=[];for(const commands of this.pages){const bytes=new TextEncoder().encode(commands.join('\n')+'\n');const content=add({stream:bytes});const page=add(`<< /Type /Page /Parent ${root} 0 R /MediaBox [0 0 ${this.w} ${this.h}] /Resources << /Font << /F1 ${fa} 0 R /F2 ${fb} 0 R >> >> /Contents ${content} 0 R >>`);kids.push(page);}objs[root]=`<< /Type /Pages /Count ${kids.length} /Kids [${kids.map(k=>k+' 0 R').join(' ')}] >>`;const catalog=add(`<< /Type /Catalog /Pages ${root} 0 R >>`);const chunks=[];let cursor=0;const write=v=>{const b=typeof v==='string'?new TextEncoder().encode(v):v;chunks.push(b);cursor+=b.length;};write('%PDF-1.4\n');const offsets=[0];objs.slice(1).forEach((o,i)=>{offsets[i+1]=cursor;write(`${i+1} 0 obj\n`);if(typeof o==='string')write(o+'\n');else{write(`<< /Length ${o.stream.length} >>\nstream\n`);write(o.stream);write('\nendstream\n');}write('endobj\n');});const xref=cursor;write(`xref\n0 ${objs.length}\n0000000000 65535 f \n`);for(let i=1;i<objs.length;i++)write(`${String(offsets[i]).padStart(10,'0')} 00000 n \n`);write(`trailer\n<< /Size ${objs.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(chunks,{type:'application/pdf'});}
}
window.generateMouPdf=async function({rows=[],filters={}}={}){
 const data=Array.isArray(rows)?rows:[];
 const doc=new PDF();doc.heading('MoU & Collaborations Performance Report','Executive summary  |  University of Lahore');
 doc.text('TENTATIVE INSTITUTIONAL REPORT',44,149,9,true,palette.green);doc.text('Generated '+new Date().toLocaleString(),570,149,9,false,palette.grey);doc.y=182;
 doc.cards([['MoU Records',data.length],['Countries',unique(data,'Country')],['Partner Institutions',unique(data,'Partner Institution')],['Faculties',unique(data,'Faculty')]]);
 doc.text('REPORT FILTERS',44,320,12,true,palette.navy);doc.line(44,344,doc.w-44,344);let ypos=360;
 for(const [key,label] of [['faculty','Faculty'],['department','Department'],['country','Country'],['type','MoU Type']]){doc.text(label,45,ypos,9,true,palette.green);doc.wrap(filters[key]&&filters[key]!=='All'?filters[key]:'All',530,10).slice(0,2).forEach((v,i)=>doc.text(v,210,ypos+i*12,10,false,palette.ink));ypos+=34;}
 const sections=[['Partnerships by Country','Country-wise institutional engagement',group(data,'Country')],['Collaboration Type Breakdown','Academic, industry and other partnership types',group(data,'MoU Type')],['MoU Progress & Status','MoU processing and completion stages',group(data,'Status')],['MoUs by Faculty','Faculty involvement in MoUs',group(data,'Faculty')],['MoUs by Department','Department participation',group(data,'Department')]];
 for(const [title,subtitle,entries] of sections)doc.breakdownPage(title,subtitle,entries);
 doc.table('Partner Institutions',['Partner Institution','MoU Records'],group(data,'Partner Institution').map(([n,c])=>[n,fmt(c)]),[78,22]);
 doc.table('Detailed MoU Records',['Partner Institution','Faculty','Department','Country','MoU Type','Status'],data.map(r=>[r['Partner Institution'],r.Faculty,r.Department,r.Country,r['MoU Type'],r.Status]),[26,18,20,11,12,13]);
 const blob=doc.output(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='UOL_MoU_Executive_Style_Report_'+new Date().toISOString().slice(0,10)+'.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);return true;
};
})();
